### ISSUE TITLE
errors while running py.test

### ISSUE THREAD

**Issue by ajavvadi** [janelia-flyem/gala#77] opened 2016-03-02 07:02 UTC
Hello,

I am trying to use GALA. When I run py.test, I got the following output. This might be some stupid installation problem of mine but I am not able to figure what's going wrong. I tried building NeruoProof and tried copying the libraries (for example, "libNeuroProofPriority ") to the gala-master folder and ran py.test but the output persisted.

Any help is very appreciated!

Following is the error:
`==================================== ERRORS ====================================
___________ ERROR collecting build/lib.linux-x86_64-3.5/gala/auto.py ___________
build/lib.linux-x86_64-3.5/gala/auto.py:2: in <module>
    import libNeuroProofPriority as neuroproof
E   ImportError: No module named 'libNeuroProofPriority'
___ ERROR collecting build/lib.linux-x86_64-3.5/gala/segmentation_stitch.py ____
build/lib.linux-x86_64-3.5/gala/segmentation_stitch.py:20: in <module>
    from . import imio, morpho, classify, evaluate, app_logger, session_manager, pixel, features, stack_np
build/lib.linux-x86_64-3.5/gala/stack_np.py:2: in <module>
    import libNeuroProofRag as neuroproof
E   ImportError: No module named 'libNeuroProofRag'
_________ ERROR collecting build/lib.linux-x86_64-3.5/gala/stack_np.py _________
build/lib.linux-x86_64-3.5/gala/stack_np.py:2: in <module>
    import libNeuroProofRag as neuroproof
E   ImportError: No module named 'libNeuroProofRag'
__________ ERROR collecting build/lib.linux-x86_64-3.5/gala/stitch.py __________
build/lib.linux-x86_64-3.5/gala/stitch.py:11: in <module>
    from gala import single_arg_read_image_stack
E   ImportError: cannot import name 'single_arg_read_image_stack'
_______ ERROR collecting build/lib.linux-x86_64-3.5/gala/test_package.py _______
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
E     File "/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/test_package.py", line 147
E       os.makedirs(writedir)
E                           ^
E   TabError: inconsistent use of tabs and spaces in indentation
_______ ERROR collecting build/lib.linux-x86_64-3.5/gala/test_package.py _______
../../../miniconda3/envs/gala/lib/python3.5/site-packages/_pytest/python.py:610: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
E     File "/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/test_package.py", line 147
E       os.makedirs(writedir)
E                           ^
E   TabError: inconsistent use of tabs and spaces in indentation
_________ ERROR collecting build/lib.linux-x86_64-3.5/gala/valprob.py __________
build/lib.linux-x86_64-3.5/gala/valprob.py:2: in <module>
    import libNeuroProofPriority as neuroproof
E   ImportError: No module named 'libNeuroProofPriority'
________________________ ERROR collecting gala/agglo.py ________________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.agglo', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/agglo.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/agglo.py'))
_______________________ ERROR collecting gala/agglo2.py ________________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.agglo2', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/agglo2.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/agglo2.py'))
____________________ ERROR collecting gala/annotefinder.py _____________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.annotefinder', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/annotefinder.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/annotefinder.py'))
_____________________ ERROR collecting gala/app_logger.py ______________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.app_logger', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/app_logger.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/app_logger.py'))
______________________ ERROR collecting gala/classify.py _______________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.classify', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/classify.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/classify.py'))
_______________________ ERROR collecting gala/dtypes.py ________________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.dtypes', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/dtypes.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/dtypes.py'))
______________________ ERROR collecting gala/evaluate.py _______________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.evaluate', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/evaluate.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/evaluate.py'))
_______________________ ERROR collecting gala/filters.py _______________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.filters', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/filters.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/filters.py'))
________________________ ERROR collecting gala/imio.py _________________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.imio', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/imio.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/imio.py'))
____________________ ERROR collecting gala/iterprogress.py _____________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.iterprogress', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/iterprogress.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/iterprogress.py'))
_____________________ ERROR collecting gala/mergequeue.py ______________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.mergequeue', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/mergequeue.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/mergequeue.py'))
_______________________ ERROR collecting gala/morpho.py ________________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.morpho', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/morpho.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/morpho.py'))
________________________ ERROR collecting gala/ncut.py _________________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.ncut', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/ncut.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/ncut.py'))
___________________ ERROR collecting gala/option_manager.py ____________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.option_manager', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/option_manager.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/option_manager.py'))
________________________ ERROR collecting gala/pixel.py ________________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.pixel', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/pixel.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/pixel.py'))
________________ ERROR collecting gala/segmentation_pipeline.py ________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.segmentation_pipeline', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/segmentation_pipeline.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/segmentation_pipeline.py'))
________________________ ERROR collecting gala/serve.py ________________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.serve', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/serve.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/serve.py'))
___________________ ERROR collecting gala/session_manager.py ___________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.session_manager', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/session_manager.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/session_manager.py'))
______________________ ERROR collecting gala/sparselol.py ______________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.sparselol', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/sparselol.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/sparselol.py'))
________________________ ERROR collecting gala/util.py _________________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.util', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/util.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/util.py'))
_________________________ ERROR collecting gala/viz.py _________________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.viz', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/viz.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/viz.py'))
____________________ ERROR collecting gala/features/base.py ____________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.features.base', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/features/base.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/features/base.py'))
________________ ERROR collecting gala/features/convex_hull.py _________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.features.convex_hull', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/features/convex_hull.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/features/convex_hull.py'))
__________________ ERROR collecting gala/features/default.py ___________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.features.default', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/features/default.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/features/default.py'))
___________________ ERROR collecting gala/features/graph.py ____________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.features.graph', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/features/graph.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/features/graph.py'))
_________________ ERROR collecting gala/features/inclusion.py __________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.features.inclusion', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/features/inclusion.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/features/inclusion.py'))
_____________________ ERROR collecting gala/features/io.py _____________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.features.io', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/features/io.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/features/io.py'))
________________ ERROR collecting gala/features/orientation.py _________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.features.orientation', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/features/orientation.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/features/orientation.py'))
________________ ERROR collecting gala/features/squiggliness.py ________________
../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('gala.features.squiggliness', '/home/kalyan/Desktop/GalaDirIn/gala-master/build/lib.linux-x86_64-3.5/gala/features/squiggliness.py', local('/home/kalyan/Desktop/GalaDirIn/gala-master/gala/features/squiggliness.py'))

**Comment by jni** [comment] 2016-03-02 07:12
Hi @ajavvadi!

I don't have much experience with NeuroProof, unfortunately, but I can fix the rest of your errors. =)

Firstly, how did you build gala? In order for the tests to run, you have to build it in-place, either:

```
python setup.py build_ext -i
```

or

```
python setup.py develop
```

(The latter builds in-place and then places a symlink to the working directory in your Python site-packages directory.)

Once you've built that way, the ImportMismatchErrors should go away. That's a quirk of py.test that I haven't figured out yet how to make robust.

Next, you should make sure that you run py.test from the gala root directory, so that it picks up the setup.cfg file, which tells it to ignore a whole bunch of files, including those that depend on neuroproof.

These solutions are all a little bit makeshift and temporary, but hopefully they should get you up and running for now! Let me know if they help! (Or if they don't!)

(A good way to check, btw, is to look at the .travis.yml file, which contains build and test commands. =)

**Comment by ajavvadi** [comment] 2016-03-02 07:34
Thanks for the prompt reply  @jni !

I, actually,didn't do either of those two steps. I was following the instructions which said I could use "pip install gala" or "python setup.py install".  I used the latter and then i installed the requirements using minconda as was pointed out. I will do this from scratch now and let you know how it turns out.

Again, thanks for the help!

**Comment by ajavvadi** [comment] 2016-03-02 08:17
@jni 
Yup! I built the code with the second option and then ran py.test from the root directory. Some of the import errors are gone but the ones related to neuroproof errors remained. Check out the output below:

`_______________________________________________________________________________________ ERROR collecting gala/auto.py _______________________________________________________________________________________
auto.py:2: in <module>
    import libNeuroProofPriority as neuroproof
E   ImportError: No module named 'libNeuroProofPriority'
_______________________________________________________________________________ ERROR collecting gala/segmentation_stitch.py ________________________________________________________________________________
segmentation_stitch.py:20: in <module>
    from . import imio, morpho, classify, evaluate, app_logger, session_manager, pixel, features, stack_np
stack_np.py:2: in <module>
    import libNeuroProofRag as neuroproof
E   ImportError: No module named 'libNeuroProofRag'
_____________________________________________________________________________________ ERROR collecting gala/stack_np.py _____________________________________________________________________________________
stack_np.py:2: in <module>
    import libNeuroProofRag as neuroproof
E   ImportError: No module named 'libNeuroProofRag'
______________________________________________________________________________________ ERROR collecting gala/stitch.py ______________________________________________________________________________________
stitch.py:11: in <module>
    from gala import single_arg_read_image_stack
E   ImportError: cannot import name 'single_arg_read_image_stack'
___________________________________________________________________________________ ERROR collecting gala/test_package.py ___________________________________________________________________________________
../../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
E     File "/home/kalyan/Desktop/GalaDirIn/gala-master/gala/test_package.py", line 147
E       os.makedirs(writedir)
E                           ^
E   TabError: inconsistent use of tabs and spaces in indentation
___________________________________________________________________________________ ERROR collecting gala/test_package.py ___________________________________________________________________________________
../../../../miniconda3/envs/gala/lib/python3.5/site-packages/_pytest/python.py:610: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../../../../miniconda3/envs/gala/lib/python3.5/site-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
E     File "/home/kalyan/Desktop/GalaDirIn/gala-master/gala/test_package.py", line 147
E       os.makedirs(writedir)
E                           ^
E   TabError: inconsistent use of tabs and spaces in indentation
_____________________________________________________________________________________ ERROR collecting gala/valprob.py ______________________________________________________________________________________
valprob.py:2: in <module>
    import libNeuroProofPriority as neuroproof
E   ImportError: No module named 'libNeuroProofPriority'`

**Comment by jni** [comment] 2016-03-02 09:40
@ajavvadi yeah those instructions assume you want to *use* gala, not test it. =P Ideally one would imply the other but that's not the case yet. =)

 That's super weird though! What do you get when you type `cat setup.cfg`? It should be:

```
 ~/projects/gala (speedup)$ cat setup.cfg
[pytest]
; ignore files dependent on NeuroProof (--ignore gala/*.py)
; ignore scripts for generating test data (--ignore tests/**.py)
; run doctests (--doctest-modules)
; run coverage (--cov .)
; report uncovered lines (--cov-report term-missing)
addopts = --ignore doc --ignore gala/test_package.py --ignore tests/toy-data --ignore gala/auto.py --ignore gala/segmentation_stitch.py --ignore gala/stack_np.py --ignore gala/stitch.py --ignore gala/valprob.py --ignore tests/_util/generate-test-results.py --ignore tests/example-data/example.py --doctest-modules --cov . --cov-report term-missing
```

As indicated by the comments in that config file, those files should be ignored by pytest... What version of pytest are you on? (`py.test --version`)?

**Comment by ajavvadi** [comment] 2016-03-02 22:50
@jni 

I got the same output for cat setup.cfg. I am pasting it below...

`(gala)kalyan@kalyan-XPS-L501X ~/Documents/Gala/gala-master $ cat setup.cfg
[pytest]
; ignore files dependent on NeuroProof (--ignore gala/*.py)
; ignore scripts for generating test data (--ignore tests/**.py)
; run doctests (--doctest-modules)
; run coverage (--cov .)
; report uncovered lines (--cov-report term-missing)
addopts = --ignore doc --ignore gala/test_package.py --ignore tests/toy-data --ignore gala/auto.py --ignore gala/segmentation_stitch.py --ignore gala/stack_np.py --ignore gala/stitch.py --ignore gala/valprob.py --ignore tests/_util/generate-test-results.py --ignore tests/example-data/example.py --doctest-modules --cov . --cov-report term-missing
`

The py.test version is 2.8.5.

**Comment by jni** [comment] 2016-03-02 23:06
Gah! I really don't understand what's going on. Here's an idea: what happens if you run py.test with all those options manually inserted into the command-line? By the way, are you getting the coverage reports from your py.test runs?

**Comment by jni** [comment] 2017-02-03 04:56
@ajavvadi I'm going to close this issue because I can't reproduce it, and it seems you've moved on. Please reopen if it is still bugging you! Thanks for using Gala!

**Closed by jni** 2017-02-03 04:56 UTC
